libname FINANCE "C:\Users\Dell inspiron 13\Desktop\TD_FINANCE";
run;
proc means data=Finance.cisse;
var cac40 Bouygues;
run;
data finance.cisse;
set Finance.cisse;
rentacac=log(Cac40/lag(Cac40));
renbouygues=log(Bouygues/lag(Bouygues));
run;
data finance.cisse;
set finance.cisse;
rentacac2=rentacac**2;
renbouygues2=renbouygues**2;
run;
proc arima data=finance.cisse;
identify var=rentacac2;
run;
proc arima data=finance.cisse;
identify var=renbouygues2;
run;
proc arima data=Finance.cisse; /* pour obtenir les corrélogrammes */
identify var=renbouygues nlag=24;
run;

proc arima data=Finance.Cisse;
identify var=rentacac2 stationarity=(ADF=(5));
run;
proc means data=Finance.cisse;
var rentacac renbouygues;
run;
proc univariate data=Finance.Cisse;
var rentacac;
run;
proc autoreg data=Finance.Cisse;
model rentacac= /normal;
run;
proc univariate data=Finance.Cisse;
var renbouygues;
run;
proc autoreg data=Finance.Cisse;
model renbouygues= /normal;
run;
proc gplot data=Finance.cisse;
symbol i=spline v=point h=2;
plot cac40*Date;
run;
proc gplot data=Finance.cisse;
symbol i=spline v=point h=2;
plot Bouygues*Date;
run;
proc gplot data=Finance.cisse;
symbol i=spline v=point h=2;
plot rentacac*Date;
run;
proc gplot data=Finance.cisse;
symbol i=spline v=point h=2 c=red;
plot renbouygues*Date;
run;
proc arima data=Finance.Cisse;
identify var=rentacac;
run;
quit;
proc arima data=Finance.Cisse;
identify var=renbouygues;
run;
quit;

proc arima data=Finance.Cisse;
identify var=rentacac stationarity=(ADF=(0));
run;
proc arima data=Finance.Cisse;
identify var=renbouygues stationarity=(ADF=(0));
run;
proc autoreg data=Finance.Cisse;
model renbouygues=rentacac;
run;
proc autoreg data=Finance.Cisse;
model renbouygues=rentacac / ARCHTEST;
output out=Finance.residus r=resid;
run;
data Finance.Rcarre;
set Finance.residus;
Residuaucarre=resid**2;
run;
proc arima data=Finance.Rcarre;
identify var=residuaucarre;
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(q=2);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=3,q=2);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=3, mean=linear);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=3,q=2, mean=linear);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=1,q=1,type=integrated);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=1, q=1, type=exp);
run;
proc autoreg data=Finance.Rcarre;
model renbouygues=rentacac/garch=(p=1, q=1, type=threshold);
run;
proc reg data=Finance.Rcarre;
model renbouygues=rentacac/ selection= AIC BIC 
best=2;
run;
quit;

